Follow POM convention to ordering POM elements + missing deployment repositories + approval tests
fabric8-launcher/maven-model-helper pull request #115
Opened 2024-02-24 09:53 UTC by murdos

2024-02-24 10:04 UTC, gastaldi requested changes
Thank you for the PR! Never heard of this `approvaltests` library before, but it belongs to the `test` scope AFAIU

2024-02-24 10:04 UTC, gastaldi commented on pom.xml
> +            <version>22.3.2</version>
It's missing the `test` scope

2024-02-24 10:32 UTC, murdos commented on pom.xml
> +            <version>22.3.2</version>
Yes, of course! it's fixed

2024-02-24 10:44 UTC, gastaldi reviewed
Some minor nitpicks to the test

2024-02-24 10:44 UTC, gastaldi commented on src/test/java/io/fabric8/maven/MavenTest.java
> +        Model model = Maven.readModel(new FileReader(basePom.toFile()));
```suggestion
        Model model = Maven.readModel(basePom);
```

2024-02-24 10:44 UTC, gastaldi commented on src/test/java/io/fabric8/maven/MavenTest.java
> +        Model model = Maven.readModel(new FileReader(basePom.toFile()));
```suggestion
        Model model = Maven.readModel(basePom);
```

2024-02-24 10:56 UTC, gastaldi commented
Thank you for the PRs! I'll try them out and merge them if all looks good

2024-02-26 14:08 UTC, gastaldi approved these changes

2024-02-26 14:09 UTC, merged